# -*- coding: utf-8 -*-
"""Prophet

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SrRfDc3hjwsSE1Leh6hbtB3TXsUg7_lL
"""

# pip install prophet

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import json

from prophet import Prophet
from prophet.diagnostics import cross_validation, performance_metrics
from sklearn.metrics import mean_absolute_error, mean_squared_error

store1 = pd.read_csv('store1_timeseries.csv',
                      parse_dates=['Date'], index_col='Date')

split_date = '2015-06-15'
s1_train = store1[store1.index < split_date].copy()
s1_test  = store1[store1.index >= split_date].copy()

print(f"Train: {s1_train.shape} | {s1_train.index.min()} to {s1_train.index.max()}")
print(f"Test : {s1_test.shape}  | {s1_test.index.min()} to {s1_test.index.max()}")

train_prophet = s1_train.reset_index()[['Date', 'Sales', 'Promo', 'IsHoliday']].rename(
    columns={'Date': 'ds', 'Sales': 'y'})

test_prophet = s1_test.reset_index()[['Date', 'Sales', 'Promo', 'IsHoliday']].rename(
    columns={'Date': 'ds', 'Sales': 'y'})

print(f"Min sales in train: {train_prophet['y'].min()}")
print(f"Any zeros: {(train_prophet['y'] == 0).sum()}")
print(f"\nTrain shape : {train_prophet.shape}")
print(f"Test shape  : {test_prophet.shape}")
print(train_prophet.head())

model = Prophet(
    yearly_seasonality=True,
    weekly_seasonality=True,
    daily_seasonality=False,
    seasonality_mode='multiplicative',
    changepoint_prior_scale=0.05,
    seasonality_prior_scale=10,
    interval_width=0.95
)

model.add_country_holidays(country_name='DE')

model.add_regressor('Promo')
model.add_regressor('IsHoliday')

model.fit(train_prophet[['ds', 'y', 'Promo', 'IsHoliday']])
print("Prophet model fitted successfully")

future = test_prophet[['ds', 'Promo', 'IsHoliday']].copy()
forecast = model.predict(future)

print("Forecast columns available:")
print([c for c in forecast.columns if any(k in c for k in
      ['yhat', 'trend', 'seasonal', 'holiday'])])
print(f"\nForecast shape: {forecast.shape}")
print(forecast[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].head(10))

def mape(actual, predicted):
    actual, predicted = np.array(actual), np.array(predicted)
    mask = actual != 0
    return np.mean(np.abs((actual[mask] - predicted[mask]) / actual[mask])) * 100

actuals = test_prophet['y'].values
preds   = forecast['yhat'].values

preds = np.clip(preds, 0, None)

mae      = mean_absolute_error(actuals, preds)
rmse     = np.sqrt(mean_squared_error(actuals, preds))
mape_val = mape(actuals, preds)

print("=" * 40)
print("Prophet — Store 1 Performance (Daily)")
print("=" * 40)
print(f"  MAE  : {mae:,.2f}")
print(f"  RMSE : {rmse:,.2f}")
print(f"  MAPE : {mape_val:.2f}%")
print("=" * 40)

prophet_metrics = {'Model': 'Prophet', 'MAE': mae, 'RMSE': rmse, 'MAPE': mape_val}

fig, ax = plt.subplots(figsize=(14, 6))


train_tail = train_prophet.tail(90)
ax.plot(train_tail['ds'], train_tail['y'],
        color='steelblue', linewidth=1.2, label='Training Data')

ax.plot(test_prophet['ds'], test_prophet['y'],
        color='black', linewidth=1.5, linestyle='--', label='Actual Sales')


ax.plot(forecast['ds'], forecast['yhat'],
        color='coral', linewidth=1.5, label='Prophet Forecast')

ax.fill_between(forecast['ds'],
                forecast['yhat_lower'],
                forecast['yhat_upper'],
                color='coral', alpha=0.2, label='95% Confidence Interval')

ax.axvline(pd.Timestamp(split_date), color='gray',
           linestyle=':', linewidth=1, label='Forecast Start')
ax.set_title(f'Store 1 — Prophet Forecast vs Actuals\nMAPE: {mape_val:.2f}% | RMSE: {rmse:,.0f}',
             fontsize=13, fontweight='bold')
ax.set_xlabel('Date')
ax.set_ylabel('Daily Sales')
ax.legend()
ax.grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig('01_prophet_forecast.png', dpi=150, bbox_inches='tight')
plt.show()

fig = model.plot_components(forecast)
fig.set_size_inches(14, 10)
plt.suptitle('Prophet — Forecast Components (Store 1)',
             fontsize=13, fontweight='bold', y=1.01)
plt.tight_layout()
plt.savefig('02_prophet_components.png', dpi=150, bbox_inches='tight')
plt.show()

print("Running cross validation — takes a few minutes...")

df_cv = cross_validation(
    model,
    initial='500 days',
    period='90 days',
    horizon='45 days',
    parallel=None
)

df_perf = performance_metrics(df_cv)

print("\nCross Validation Performance:")
print(df_perf[['horizon', 'mae', 'rmse', 'mape']].tail(10))

from prophet.plot import plot_cross_validation_metric

fig = plot_cross_validation_metric(df_cv, metric='mape')
fig.set_size_inches(12, 5)
plt.title('Prophet — MAPE across forecast horizons', fontweight='bold')
plt.tight_layout()
plt.savefig('03_cv_mape.png', dpi=150, bbox_inches='tight')
plt.show()



with open('prophet_metrics.json', 'w') as f:
    json.dump(prophet_metrics, f)

print("=" * 45)
print("Prophet — Store 1 Results")
print("=" * 45)
print(f"{'Model':<12} {'MAE':>10} {'RMSE':>10} {'MAPE':>10}")
print("-" * 45)
print(f"{prophet_metrics['Model']:<12} {prophet_metrics['MAE']:>10,.2f} {prophet_metrics['RMSE']:>10,.2f} {prophet_metrics['MAPE']:>10.2f}%")
print("=" * 45)

